//User
export const SIGN_UP = "SIGN_UP"
export const SIGN_IN = "SIGN_IN"
export const SIGN_OUT = "SIGN_OUT"
export const REQUEST_ADMIN_RIGHTS = "REQUEST_ADMIN_RIGHTS"

//Patient List
export const CREATE_NEW_PATIENT = "CREATE_NEW_PATIENT"
export const READ_PATIENT_LIST = "READ_PATIENT_LIST"
export const READ_PATIENT_DATA = "READ_PATIENT_DATA"
export const UPDATE_PATIENT_DATA = "UPDATE_PATIENT_DATA"
export const DELETE_PATIENT_DATA = "DELETE_PATIENT_DATA"
export const READ_PATIENT_NOTE_LIST = "READ_PATIENT_NOTE_LIST"
export const CREATE_PATIENT_NOTE = "CREATE_PATIENT_NOTE"
export const READ_PATIENT_NOTE = "READ_PATIENT_NOTE"
export const UPDATE_PATIENT_NOTE = "UPDATE_PATIENT_NOTE"
export const DELETE_PATIENT_NOTE = "DELETE_PATIENT_NOTE"
export const SET_WORKUP_INDEX = "SET_WORKUP_INDEX"
export const TOGGLE_NOTE_EXPORTED = "TOGGLE_NOTE_EXPORTED"

//Module
export const CREATE_NEW_MODULE = "CREATE_NEW_MODULE"
export const CREATE_NEW_PUBLIC_MODULE = "CREATE_NEW_PUBLIC_MODULE"
export const READ_MODULE = "READ_MODULE"
export const GET_MY_MODULES = "GET_MY_MODULES"
export const UPDATE_MODULE = "UPDATE_MODULE"
export const DELETE_MODULE = "DELETE_MODULE"
export const TOGGLE_MODULE_LIST_STATE_PUBLIC_OR_PRIVATE =
    "TOGGLE_MODULE_LIST_STATE_PUBLIC_OR_PRIVATE"
export const CHANGE_MODULE_LIST_STATE_CATEGORY = "CHANGE_MODULE_LIST_STATE_CATEGORY"

//Modal
export const OPEN_CREATE_NEW_PATIENT_MODAL = "OPEN_CREATE_NEW_PATIENT_MODAL"
export const CLOSE_CREATE_NEW_PATIENT_MODAL = "CLOSE_CREATE_NEW_PATIENT_MODAL"
export const OPEN_CREATE_NEW_NOTE_MODAL = "OPEN_CREATE_NEW_NOTE_MODAL"
export const CLOSE_CREATE_NEW_NOTE_MODAL = "CLOSE_CREATE_NEW_NOTE_MODAL"
export const OPEN_IMPORT_MODULE_MODAL = "OPEN_IMPORT_MODULE_MODAL"
export const CLOSE_IMPORT_MODULE_MODAL = "CLOSE_IMPORT_MODULE_MODAL"

//Search
export const SEARCH_DIAGNOSIS_AUTOCOMPLETE = "SEARCH_DIAGNOSIS_AUTOCOMPLETE"
export const SEARCH_DATAPOINT_AUTOCOMPLETE = "SEARCH_DATAPOINT_AUTOCOMPLETE"
export const SEARCH_DRUG_AUTOCOMPLETE = "SEARCH_DRUG_AUTOCOMPLETE"
export const GET_DIAGNOSIS_DETAIL = "GET_DIAGNOSIS_DETAIL"
export const GET_DATAPOINT_DETAIL = "GET_DATAPOINT_DETAIL"
export const GET_DRUG_DETAIL = "GET_DRUG_DETAIL"
export const SEARCH_PUBLIC_MODULE = "SEARCH_PUBLIC_MODULE"

//Admin
export const CREATE_DIAGNOSIS_DATA = "CREATE_DIAGNOSIS_DATA"
export const CREATE_DATAPOINT_DATA = "CREATE_DATAPOINT_DATA"
export const CREATE_DRUG_DATA = "CREATE_DRUG_DATA"
export const UPDATE_DIAGNOSIS_DATA = "UPDATE_DIAGNOSIS_DATA"
export const UPDATE_DATAPOINT_DATA = "UPDATE_DATAPOINT_DATA"
export const UPDATE_DRUG_DATA = "UPDATE_DRUG_DATA"
