//User
export const SIGN_UP = "SIGN_UP"
export const SIGN_IN = "SIGN_IN"
export const SIGN_OUT = "SIGN_OUT"

//Patient List
export const CREATE_NEW_PATIENT = "CREATE_NEW_PATIENT"
export const READ_PATIENT_LIST = "READ_PATIENT_LIST"
export const UPDATE_PATIENT_DATA = "UPDATE_PATIENT_DATA"
export const DELETE_PATIENT_DATA = "DELETE_PATIENT_DATA"

//Module
export const CREATE_NEW_MODULE = "CREATE_NEW_MODULE"
export const READ_MODULE = "READ_MODULE"
export const UPDATE_MODULE = "UPDATE_MODULE"
export const DELETE_MODULE = "DELETE_MODULE"

//Modal
export const OPEN_CREATE_NEW_PATIENT_MODAL = "OPEN_CREATE_NEW_PATIENT_MODAL"
export const CLOSE_CREATE_NEW_PATIENT_MODAL = "CLOSE_CREATE_NEW_PATIENT_MODAL"

//Search
export const SEARCH_DIAGNOSIS_AUTOCOMPLETE = "SEARCH_DIAGNOSIS_AUTOCOMPLETE"
export const SEARCH_DATAPOINT_AUTOCOMPLETE = "SEARCH_DATAPOINT_AUTOCOMPLETE"
